# template.sub
# starter submit file for CHTC jobs
# import conda environment

universe = vanilla
log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = conda.sh
arguments = hello conda

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = py-dat-sci.tar.gz
requirements = (OpSysMajorVer =?= 7)

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue 1
